mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdSearchView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment', 
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', 
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'autos'
urlpatterns = [
    path("", views.MainView.as_view(), name="all"),
    path("main/create/", views.AutoCreate.as_view(), name= "auto_create"),
    path("main/<int:pk>/update/", views.AutoUpdate.as_view(), name= "auto_update"),
    path("main/<int:pk>/delete/", views.AutoDelete.as_view(), name= "auto_delete"),
    path("lookup/", views.MakeView.as_view(), name="make_list"),
    path("lookup/create/", views.MakeCreate.as_view(), name= "make_create"),
    path("lookup/<int:pk>/update/", views.MakeUpdate.as_view(), name="make_update"),
    path("lookup/<int:pk>/delete/", views.MakeDelete.as_view(), name="make_delete"),
    ]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('ads.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('vehicles/', include('vehicles.urls')),
    path('searchbar/', include('searchbar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cashmanagement/', include('cashmanagement.urls')),
    path('newapp/', include('newapp.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')
# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

mysite/vehicles/urls.py
from django.urls import path
from . import views
from .views import AplicationDetailView, AplicationPhotoUploadView, AplicationPhotoDeleteView, AplicationList

app_name = 'vehicles'
urlpatterns = [
    path('', views.AplicationList.as_view(), name='all'),
    path('load_more/', views.LoadMoreAplicationsView.as_view(), name='load_more_aplications'),
    path('ajax_search/', views.ajax_search_view, name='ajax_search'),

    
    path('aplication/<int:pk>/', AplicationDetailView.as_view(), name='aplication_detail'),
    path('aplication/<int:pk>/upload/', AplicationPhotoUploadView.as_view(), name='upload_photo'),
    path('photo/delete/<int:pk>/', AplicationPhotoDeleteView.as_view(), name='delete_photo'),

    # Application CRUD
    path("main/create/", views.AplicationCreate.as_view(), name="aplication_create"),
    path("main/<int:pk>/update/", views.AplicationUpdate.as_view(), name="aplication_update"),
    path("main/<int:pk>/delete/", views.AplicationDelete.as_view(), name="aplication_delete"),

    # Make CRUD
    path("make/", views.MakeView.as_view(), name="make_list"),
    path("make/create/", views.MakeCreate.as_view(), name="make_create"),
    path("make/<int:pk>/update/", views.MakeUpdate.as_view(), name="make_update"),
    path("make/<int:pk>/delete/", views.MakeDelete.as_view(), name="make_delete"),

    # Year CRUD
    path("year/", views.YearView.as_view(), name="year_list"),
    path("year/create/", views.YearCreate.as_view(), name="year_create"),
    path('year/<int:pk>/update/', views.YearUpdate.as_view(), name='year_update'),
    path("year/<int:pk>/delete/", views.YearDelete.as_view(), name="year_delete"),

    # Model CRUD
    path("model/", views.ModelView.as_view(), name="model_list"),
    path("model/create/", views.ModelCreate.as_view(), name="model_create"),
    path("model/<int:pk>/update/", views.ModelUpdate.as_view(), name="model_update"),
    path("model/<int:pk>/delete/", views.ModelDelete.as_view(), name="model_delete"),

    # Segment CRUD
    path("segment/", views.SegmentView.as_view(), name="segment_list"),
    path("segment/create/", views.SegmentCreate.as_view(), name="segment_create"),
    path("segment/<int:pk>/update/", views.SegmentUpdate.as_view(), name="segment_update"),
    path("segment/<int:pk>/delete/", views.SegmentDelete.as_view(), name="segment_delete"),

    # Category CRUD
    path('category/', views.CategoryView.as_view(), name='category_list'),
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),

    # Part CRUD
    path("part/", views.PartListView.as_view(), name="part_list"),
    path("part/create/", views.PartCreate.as_view(), name="part_create"),
    path("part/<int:pk>/update/", views.PartUpdate.as_view(), name="part_update"),
    path("part/<int:pk>/delete/", views.PartDelete.as_view(), name="part_delete"),
    path('aplication/<int:pk>/', views.PartDelete.as_view(), name="part_detail"), #queda pendiente agregar la pagina de part_detail

    #-------------------------------------------URLS para modelo "Property" obsoleto-----------------------------------------------
    # # Property CRUD
    # path("property/", views.PropertyView.as_view(), name="property_list"),
    # path("property/create/", views.PropertyCreate.as_view(), name="property_create"),
    # path("property/<int:pk>/update/", views.PropertyUpdate.as_view(), name="property_update"),
    # path("property/<int:pk>/delete/", views.PropertyDelete.as_view(), name="property_delete"),
    #------------------------------------------------------------------------------------------------------------------------------

]

mysite/vehicles/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
from mptt.models import MPTTModel, TreeForeignKey

class BaseModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(default=timezone.now, editable=False)
    created_by = models.ForeignKey(User, related_name='created_%(class)s_set', on_delete=models.CASCADE, default=1)
    updated_by = models.ForeignKey(User, related_name='updated_%(class)s_set', on_delete=models.CASCADE, default=1)


    class Meta:
        abstract = True

class Make(BaseModel):
    make = models.CharField(
        max_length=200,
        help_text='Enter a make (e.g. Yamaha)',
        validators=[MinLengthValidator(2, "Make must be greater than 1 character")],
        unique=True
    )

    searchable_fields = ['make']

    def __str__(self):
        return self.make

class Year(BaseModel):
    year = models.PositiveIntegerField(
        help_text='Enter a year (e.g. 1995)',
        unique=True
    )

    def __str__(self):
        return str(self.year)

class Model(BaseModel):
    model = models.CharField(
        max_length=200,
        help_text='Enter a model (e.g. YZ 250FX)',
        validators=[MinLengthValidator(2, "Model must be greater than 1 character")],
        unique=True
    )

    def __str__(self):
        return self.model

class Segment(BaseModel):
    segment = models.CharField(
        max_length=30,
        help_text='Enter a segment (e.g. Off-Road, Trail)',
        validators=[MinLengthValidator(2, "Segment must be greater than 1 character")],
        unique=True,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.segment

class Aplication(BaseModel):
    market_choices = [
        ('US', 'United States'),
        ('EU', 'Europe'),
        ('ARG', 'Argentina'),
        ('AU', 'Australia'),
    ]
    
    segment = models.ForeignKey(Segment, on_delete=models.CASCADE)
    make = models.ForeignKey(Make, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    market = models.CharField(max_length=3, choices=market_choices)
    
    searchable_fields = ['segment', 'make', 'year', 'model', 'market']

    
    
    
    def __str__(self):
        return f"{self.segment} > {self.make} > {self.year} > {self.model}"

class AplicationPhoto(BaseModel):
    aplication = models.ForeignKey(Aplication, related_name='photos', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='aplication_photos/')

class Category(MPTTModel, BaseModel):
    category = models.CharField(
        max_length=200,
        help_text="Enter a category (e.g. Engine, Frame, Suspension)",
        validators=[MinLengthValidator(2, 'Categories must be greater than 1 character')]
    )
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['category']

    def __str__(self):
        return self.category
    
    
#-----------------------------------------------Modelo obsoleto----------------------------------------------------------
# class SubCategory(MPTTModel, BaseModel):
#     subcategory = models.CharField(
#         max_length=200,
#         help_text="Enter a subcategory name",
#         validators=[MinLengthValidator(2, 'Subcategories must be greater than 1 character')]
#     )
#     category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
#     parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

#     def __str__(self):
#         return self.subcategory
#-----------------------------------------------Modelo obsoleto----------------------------------------------------------
# class Property(BaseModel):
#     name = models.CharField(
#         max_length=100,
#         help_text="Enter the property name (e.g. Internal Diameter, External Diameter, Material)"
#     )

#     def __str__(self):
#         return self.name


class Part(BaseModel):
    sku = models.CharField(max_length=50, db_index=True , help_text="Enter de SKU", validators=[MinLengthValidator(2, "SKU must be greater than 1 character")])
    name = models.CharField(
        max_length=100, db_index= True,
        help_text="Enter the general part name (e.g. Spark Plug)",
        validators=[MinLengthValidator(2, "Part name must be greater than 1 character")]
    )
    categories = models.ManyToManyField(Category, related_name='parts')
    applications = models.ManyToManyField(Aplication, related_name='parts')
    description = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    searchable_fields = ['sku', 'name', 'categories', 'aplications', 'description','notes']


    def __str__(self):
        categories_str = ' > '.join([cat.name for cat in self.categories.all()])
        properties_str = ', '.join([f"{prop.property}: {prop.value}" for prop in self.properties.all()])
        return f"{self.name}, {properties_str}, in {categories_str}"



class PartProperty(BaseModel):
    part = models.ForeignKey('Part', related_name='properties', on_delete=models.CASCADE)
    property = models.CharField(max_length=100, help_text="Enter the property name (e.g. Internal Diameter, External Diameter, Material)")
    value = models.CharField(max_length=200, help_text="Enter the value of the property (e.g. 50mm, Steel)")

    def __str__(self):
        return f"{self.property}: {self.value}"
    


@receiver(pre_save, sender=BaseModel)
def set_default_user(sender, instance, **kwargs):
    if not instance.pk:  # Only for new objects
        default_user = User.objects.get(pk=1)
        if not instance.created_by:
            instance.created_by = default_user
        instance.updated_by = default_user

mysite/vehicles/forms.py
# forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from vehicles.models import Make, Year, Model, Segment, Category, Part, PartProperty, Aplication, AplicationPhoto
from django.forms.models import inlineformset_factory







class MakeForm(forms.ModelForm):
    class Meta:
        model = Make
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class YearForm(forms.ModelForm):
    class Meta:
        model = Year
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class ModelForm(forms.ModelForm):
    class Meta:
        model = Model
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class SegmentForm(forms.ModelForm):
    class Meta:
        model = Segment
        fields = '__all__'
        exclude = ['created_by', 'updated_by']


class AplicationForm(forms.ModelForm):
    class Meta:
        model = Aplication
        fields = ['segment', 'make', 'year', 'model', 'market']

class AplicationPhotoForm(forms.ModelForm):
    class Meta:
        model = AplicationPhoto
        fields = ['photo'] 




class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category', 'parent']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Add Category'))



class PartForm(forms.ModelForm):
    class Meta:
        model = Part
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class PartPropertyForm(forms.ModelForm):
    class Meta:
        model = PartProperty
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

# Formset para manejar múltiples propiedades de una parte
PartPropertyFormSet = inlineformset_factory(
    Part, PartProperty, 
    form = PartPropertyForm, 
    extra=1,  # Número de formularios vacíos a mostrar
    can_delete=True  # Permite eliminar propiedades
)

# class PropertyForm(forms.ModelForm):
#     class Meta:
#         model = Property
#         fields = '__all__'
#         exclude = ['created_by', 'updated_by']

mysite/vehicles/templates/vehicles/deprecatedtemplates/aplication_rows.html
{% for aplication in aplication_list %}
<tr class="auto-row" data-href="{% url 'vehicles:aplication_update' aplication.id %}">
  <td>{{ aplication.segment }}</td>  
  <td>{{ aplication.make }}</td>
  <td>{{ aplication.year }}</td>
  <td>{{ aplication.model }}</td>
  <td>
    <a href="{% url 'vehicles:aplication_update' aplication.id %}">Update</a> |
    <a href="{% url 'vehicles:aplication_delete' aplication.id %}">Delete</a>
  </td>
</tr>
{% endfor %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/make_list.html
{% extends "base_bootstrap.html" %}

{% block content %}

{% load static %}  

{% load crispy_forms_tags %}
<style>
    .centered-form {
        max-width: 600px; /* Establece el ancho máximo deseado */
        margin: 0 auto; /* Centra el formulario horizontalmente */
    }
</style>

  <div class="row">
    <div class="col-md-7">
      <h1>Makes List <h5><a href="{% url 'vehicles:all' %}">Return to Vehicles</a></h5></h1>

      <input id="search_here" class='form-control mb-3 mt-3' placeholder="type here to search.." />

      <div id="results">
        {% if make_list %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody id="table-body">
            {% for make in make_list %}
            <tr>
              <td>{{ make.make }}</td>
              <td>
                <a href="{% url 'vehicles:make_update' make.id %}">Update</a> |
                <a href="{% url 'vehicles:make_delete' make.id %}">Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
          <p>There are no makes in the library.</p>
        {% endif %}
      </div>
    </div>
    <div class="col-md-5">

      <h2>Add a Make</h2>
      <form action="{% url 'vehicles:make_create' %}" method="post" id="makeForm">
        {% csrf_token %}
        <table>
        {{ form|crispy }}
        </table>
        {% if form.errors %}
          <p style="color: red;">{{ form.errors }}</p>
        {% endif %}
        <input type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/search_table.js' %}"></script>
<script>
    const data = JSON.parse('{{ make_list_json|escapejs }}');
    const headers = JSON.parse('{{ headers|escapejs }}');
    const fields = JSON.parse('{{ fields|escapejs }}');
    const title = '{{ title }}';
    
    initSearchTable(data, headers, fields, title);
</script>
{% endblock scripts %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/model_list.html
{% extends "base_bootstrap.html" %}


{% block content %}

{% load crispy_forms_tags %}

    <style>
        .centered-form {
            max-width: 600px; /* Establece el ancho máximo deseado */
            margin: 0 auto; /* Centra el formulario horizontalmente */
        }
    </style>
  <div class="row">
    <div class="col-md-7">
      <h1>Models List <h5><a href="{% url 'vehicles:all'  %}">Return to Vehicles</a></h5></h1>
      {% if model_list %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Model</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for model in model_list %}
          <tr>
            <td>{{ model.model }}</td>
            <td>
              <a href="{% url 'vehicles:model_update' model.id %}">Update</a> |
              <a href="{% url 'vehicles:model_delete' model.id %}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        <p>There are no models in the library.</p>
      {% endif %}
    </div>
    <div class="col-md-5">



      <h2>Add a Model</h2>
      <form action="{% url 'vehicles:model_create' %}" method="post" class="centered-form">
        {% csrf_token %}
        <table>
        {{ form|crispy }}
        </table>
        <input type="submit" value="Submit">
      </form>


    </div>

  </div>
{% endblock %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/partproperty_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Category-Property</h1>

<p>Are you sure you want to delete the Category-Property: <b>{{ catproperty}}</b> ?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/partproperty_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
{% load crispy_forms_tags %}

<style>
    .centered-form {
        max-width: 600px; /* Establece el ancho máximo deseado */
        margin: 0 auto; /* Centra el formulario horizontalmente */
    }
</style>


<form action="{% url 'vehicles:catproperty_create' %}" method="post" id="catpropertyForm" class="centered-form">
  {% csrf_token %}
  <table>
  {{ form|crispy }}
  </table>
  {% if form.errors %}
    <p style="color: red;">{{ form.errors }}</p>
  {% endif %}
  <input type="submit" value="Submit">
</form>

{% endblock %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/property_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
{% load crispy_forms_tags %}

<style>
    .centered-form {
        max-width: 600px; /* Establece el ancho máximo deseado */
        margin: 0 auto; /* Centra el formulario horizontalmente */
    }
</style>


<form action="{% url 'vehicles:property_create' %}" method="post" id="propertyForm" class="centered-form">
  {% csrf_token %}
  <table>
  {{ form|crispy }}
  </table>
  {% if form.errors %}
    <p style="color: red;">{{ form.errors }}</p>
  {% endif %}
  <input type="submit" value="Submit">
</form>

{% endblock %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/segment_list.html
{% extends "base_bootstrap.html" %}


{% block content %}

{% load crispy_forms_tags %}

    <style>
        .centered-form {
            max-width: 600px; /* Establece el ancho máximo deseado */
            margin: 0 auto; /* Centra el formulario horizontalmente */
        }
    </style>
  <div class="row">
    <div class="col-md-7">
      <h1>Segment List <h5><a href="{% url 'vehicles:all'  %}">Return to Vehicles</a></h5></h1>
      {% if segment_list %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Segment</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for segment in segment_list %}
          <tr>
            <td>{{ segment.segment }}</td>
            <td>
              <a href="{% url 'vehicles:segment_update' segment.id %}">Update</a> |
              <a href="{% url 'vehicles:segment_delete' segment.id %}">Delete</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
        <p>There are no segments in the library.</p>
      {% endif %}
    </div>
    <div class="col-md-5">



      <h2>Add a Segment</h2>
      <form action="{% url 'vehicles:segment_create' %}" method="post" class="centered-form">
        {% csrf_token %}
        <table>
        {{ form|crispy }}
        </table>
        <input type="submit" value="Submit">
      </form>


    </div>

  </div>
{% endblock %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/vehicle_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/vehicles/templates/vehicles/deprecatedtemplates/year_list.html
{% extends "base_bootstrap.html" %}

{% load crispy_forms_tags %}

<style>
    .centered-form {
        max-width: 600px; /* Establece el ancho máximo deseado */
        margin: 0 auto; /* Centra el formulario horizontalmente */
    }
    .table-responsive{
      max-height: 300px;
    }
</style>

{% block content %}
  <div class="row">
    <div class="col-md-7">
      <h1>Years List <h5><a href="{% url 'vehicles:all'  %}">Return to Vehicles</a></h5></h1>

      <input id="search_here" class='form-control mb-3 mt-3' placeholder="type here to search.." />
      
      <div id="results">
        {% if year_list %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Year</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for year in year_list %}
            <tr>
              <td>{{ year.year }}</td>
              <td>
                <a href="{% url 'vehicles:year_update' year.id %}">Update</a> |
                <a href="{% url 'vehicles:year_delete' year.id %}">Delete</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
          <p>There are no years in the library.</p>
        {% endif %}
      </div>
    </div>  
    <div class="col-md-5">
      <h2>Add a Year</h2>
      <form action="{% url 'vehicles:year_create' %}" method="post" class="centered-form">
        {% csrf_token %}
        <table>
        {{ form|crispy }}
        </table>
        <input type="submit" value="Submit">
      </form>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script>
  const data = JSON.parse('{{ year_list_json|escapejs }}');
  console.log(data);  

  const input = document.getElementById('search_here');
  const results = document.getElementById('results'); // Actualiza solo esta parte del DOM
  console.log(input);

  let filteredArr = [];

  const displayResults = (arr) => {
    let table = `<table class="table table-hover">
                   <thead>
                     <tr>
                       <th>Year</th>
                       <th>Actions</th>
                     </tr>
                   </thead>
                   <tbody>`;
    arr.forEach(year => {
      table += `<tr>
                  <td>${year.year}</td>
                  <td>
                    <a href="/vehicles/year/${year.id}/update/">Update</a> |
                    <a href="/vehicles/year/${year.id}/delete/">Delete</a>
                  </td>
                </tr>`;
    });
    table += `</tbody></table>`;
    results.innerHTML = table;
  };

  // Display initial data
  displayResults(data);

  input.addEventListener('keyup', (e) => {
    const value = e.target.value.toLowerCase().trim();
    const words = value.split(/\s+/); // Divide la entrada en palabras separadas por espacios

    if(value === "") {
      displayResults(data);
    } else {
      filteredArr = data.filter(year => {
        const combinedText = `${year.year}`.toLowerCase();

        // Verifica que cada palabra de la entrada esté en el texto combinado
        return words.every(word => combinedText.includes(word));
      });
      console.log(filteredArr);
      displayResults(filteredArr);
    }
  });
</script>
{% endblock scripts %}