mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdSearchView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment', 
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', 
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('ads.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('vehicles/', include('vehicles.urls')),
    path('searchbar/', include('searchbar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cashmanagement/', include('cashmanagement.urls')),
    path('newapp/', include('newapp.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')
# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

mysite/searchbar/urls.py
from django.contrib import admin
from django.urls import path
from vehicles.views import AplicationList

urlpatterns = [
    path('', AplicationList.as_view(), name='mainsearch'),
]

mysite/vehicles/urls.py
from django.urls import path
from . import views
from .views import AplicationDetailView, AplicationPhotoUploadView, AplicationPhotoDeleteView, AplicationList

app_name = 'vehicles'
urlpatterns = [
    path('', views.AplicationList.as_view(), name='all'),
    path('load_more/', views.LoadMoreAplicationsView.as_view(), name='load_more_aplications'),
    path('ajax_search/', views.ajax_search_view, name='ajax_search'),

    
    path('aplication/<int:pk>/', AplicationDetailView.as_view(), name='aplication_detail'),
    path('aplication/<int:pk>/upload/', AplicationPhotoUploadView.as_view(), name='upload_photo'),
    path('photo/delete/<int:pk>/', AplicationPhotoDeleteView.as_view(), name='delete_photo'),

    # Application CRUD
    path("main/create/", views.AplicationCreate.as_view(), name="aplication_create"),
    path("main/<int:pk>/update/", views.AplicationUpdate.as_view(), name="aplication_update"),
    path("main/<int:pk>/delete/", views.AplicationDelete.as_view(), name="aplication_delete"),

    # Make CRUD
    path("make/", views.MakeView.as_view(), name="make_list"),
    path("make/create/", views.MakeCreate.as_view(), name="make_create"),
    path("make/<int:pk>/update/", views.MakeUpdate.as_view(), name="make_update"),
    path("make/<int:pk>/delete/", views.MakeDelete.as_view(), name="make_delete"),

    # Year CRUD
    path("year/", views.YearView.as_view(), name="year_list"),
    path("year/create/", views.YearCreate.as_view(), name="year_create"),
    path('year/<int:pk>/update/', views.YearUpdate.as_view(), name='year_update'),
    path("year/<int:pk>/delete/", views.YearDelete.as_view(), name="year_delete"),

    # Model CRUD
    path("model/", views.ModelView.as_view(), name="model_list"),
    path("model/create/", views.ModelCreate.as_view(), name="model_create"),
    path("model/<int:pk>/update/", views.ModelUpdate.as_view(), name="model_update"),
    path("model/<int:pk>/delete/", views.ModelDelete.as_view(), name="model_delete"),

    # Segment CRUD
    path("segment/", views.SegmentView.as_view(), name="segment_list"),
    path("segment/create/", views.SegmentCreate.as_view(), name="segment_create"),
    path("segment/<int:pk>/update/", views.SegmentUpdate.as_view(), name="segment_update"),
    path("segment/<int:pk>/delete/", views.SegmentDelete.as_view(), name="segment_delete"),

    # Category CRUD
    path('category/', views.CategoryView.as_view(), name='category_list'),
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),

    # Part CRUD
    path("part/", views.PartListView.as_view(), name="part_list"),
    path("part/create/", views.PartCreate.as_view(), name="part_create"),
    path("part/<int:pk>/update/", views.PartUpdate.as_view(), name="part_update"),
    path("part/<int:pk>/delete/", views.PartDelete.as_view(), name="part_delete"),
    path('aplication/<int:pk>/', views.PartDelete.as_view(), name="part_detail"), #queda pendiente agregar la pagina de part_detail

    #-------------------------------------------URLS para modelo "Property" obsoleto-----------------------------------------------
    # # Property CRUD
    # path("property/", views.PropertyView.as_view(), name="property_list"),
    # path("property/create/", views.PropertyCreate.as_view(), name="property_create"),
    # path("property/<int:pk>/update/", views.PropertyUpdate.as_view(), name="property_update"),
    # path("property/<int:pk>/delete/", views.PropertyDelete.as_view(), name="property_delete"),
    #------------------------------------------------------------------------------------------------------------------------------

]

mysite/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from taggit.managers import TaggableManager
from django.conf import settings

class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='ad_owner')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='comments_owned')
    tags = TaggableManager(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null= True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')

    # Shows up in the admin list
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str___(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

mysite/hello/models.py
from django.db import models

# Create your models here.

mysite/home/home/models.py
from django.db import models

# Create your models here.

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/searchbar/models.py
from django.db import models

# Create your models here.

mysite/vehicles/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import pre_save
from django.dispatch import receiver
from mptt.models import MPTTModel, TreeForeignKey

class BaseModel(models.Model):
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(default=timezone.now, editable=False)
    created_by = models.ForeignKey(User, related_name='created_%(class)s_set', on_delete=models.CASCADE, default=1)
    updated_by = models.ForeignKey(User, related_name='updated_%(class)s_set', on_delete=models.CASCADE, default=1)


    class Meta:
        abstract = True

class Make(BaseModel):
    make = models.CharField(
        max_length=200,
        help_text='Enter a make (e.g. Yamaha)',
        validators=[MinLengthValidator(2, "Make must be greater than 1 character")],
        unique=True
    )

    searchable_fields = ['make']

    def __str__(self):
        return self.make

class Year(BaseModel):
    year = models.PositiveIntegerField(
        help_text='Enter a year (e.g. 1995)',
        unique=True
    )

    def __str__(self):
        return str(self.year)

class Model(BaseModel):
    model = models.CharField(
        max_length=200,
        help_text='Enter a model (e.g. YZ 250FX)',
        validators=[MinLengthValidator(2, "Model must be greater than 1 character")],
        unique=True
    )

    def __str__(self):
        return self.model

class Segment(BaseModel):
    segment = models.CharField(
        max_length=30,
        help_text='Enter a segment (e.g. Off-Road, Trail)',
        validators=[MinLengthValidator(2, "Segment must be greater than 1 character")],
        unique=True,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.segment

class Aplication(BaseModel):
    market_choices = [
        ('US', 'United States'),
        ('EU', 'Europe'),
        ('ARG', 'Argentina'),
        ('AU', 'Australia'),
    ]
    
    segment = models.ForeignKey(Segment, on_delete=models.CASCADE)
    make = models.ForeignKey(Make, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    market = models.CharField(max_length=3, choices=market_choices)
    
    searchable_fields = ['segment', 'make', 'year', 'model', 'market']

    
    
    
    def __str__(self):
        return f"{self.segment} > {self.make} > {self.year} > {self.model}"

class AplicationPhoto(BaseModel):
    aplication = models.ForeignKey(Aplication, related_name='photos', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='aplication_photos/')

class Category(MPTTModel, BaseModel):
    category = models.CharField(
        max_length=200,
        help_text="Enter a category (e.g. Engine, Frame, Suspension)",
        validators=[MinLengthValidator(2, 'Categories must be greater than 1 character')]
    )
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['category']

    def __str__(self):
        return self.category
    
    
#-----------------------------------------------Modelo obsoleto----------------------------------------------------------
# class SubCategory(MPTTModel, BaseModel):
#     subcategory = models.CharField(
#         max_length=200,
#         help_text="Enter a subcategory name",
#         validators=[MinLengthValidator(2, 'Subcategories must be greater than 1 character')]
#     )
#     category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
#     parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

#     def __str__(self):
#         return self.subcategory
#-----------------------------------------------Modelo obsoleto----------------------------------------------------------
# class Property(BaseModel):
#     name = models.CharField(
#         max_length=100,
#         help_text="Enter the property name (e.g. Internal Diameter, External Diameter, Material)"
#     )

#     def __str__(self):
#         return self.name


class Part(BaseModel):
    sku = models.CharField(max_length=50, db_index=True , help_text="Enter de SKU", validators=[MinLengthValidator(2, "SKU must be greater than 1 character")])
    name = models.CharField(
        max_length=100, db_index= True,
        help_text="Enter the general part name (e.g. Spark Plug)",
        validators=[MinLengthValidator(2, "Part name must be greater than 1 character")]
    )
    categories = models.ManyToManyField(Category, related_name='parts')
    applications = models.ManyToManyField(Aplication, related_name='parts')
    description = models.TextField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    searchable_fields = ['sku', 'name', 'categories', 'aplications', 'description','notes']


    def __str__(self):
        categories_str = ' > '.join([cat.name for cat in self.categories.all()])
        properties_str = ', '.join([f"{prop.property}: {prop.value}" for prop in self.properties.all()])
        return f"{self.name}, {properties_str}, in {categories_str}"



class PartProperty(BaseModel):
    part = models.ForeignKey('Part', related_name='properties', on_delete=models.CASCADE)
    property = models.CharField(max_length=100, help_text="Enter the property name (e.g. Internal Diameter, External Diameter, Material)")
    value = models.CharField(max_length=200, help_text="Enter the value of the property (e.g. 50mm, Steel)")

    def __str__(self):
        return f"{self.property}: {self.value}"
    


@receiver(pre_save, sender=BaseModel)
def set_default_user(sender, instance, **kwargs):
    if not instance.pk:  # Only for new objects
        default_user = User.objects.get(pk=1)
        if not instance.created_by:
            instance.created_by = default_user
        instance.updated_by = default_user

mysite/vehicles/forms.py
# forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from vehicles.models import Make, Year, Model, Segment, Category, Part, PartProperty, Aplication, AplicationPhoto
from django.forms.models import inlineformset_factory







class MakeForm(forms.ModelForm):
    class Meta:
        model = Make
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class YearForm(forms.ModelForm):
    class Meta:
        model = Year
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class ModelForm(forms.ModelForm):
    class Meta:
        model = Model
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class SegmentForm(forms.ModelForm):
    class Meta:
        model = Segment
        fields = '__all__'
        exclude = ['created_by', 'updated_by']


class AplicationForm(forms.ModelForm):
    class Meta:
        model = Aplication
        fields = ['segment', 'make', 'year', 'model', 'market']

class AplicationPhotoForm(forms.ModelForm):
    class Meta:
        model = AplicationPhoto
        fields = ['photo'] 




class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category', 'parent']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Add Category'))



class PartForm(forms.ModelForm):
    class Meta:
        model = Part
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

class PartPropertyForm(forms.ModelForm):
    class Meta:
        model = PartProperty
        fields = '__all__'
        exclude = ['created_by', 'updated_by']

# Formset para manejar múltiples propiedades de una parte
PartPropertyFormSet = inlineformset_factory(
    Part, PartProperty, 
    form = PartPropertyForm, 
    extra=1,  # Número de formularios vacíos a mostrar
    can_delete=True  # Permite eliminar propiedades
)

# class PropertyForm(forms.ModelForm):
#     class Meta:
#         model = Property
#         fields = '__all__'
#         exclude = ['created_by', 'updated_by']

mysite/searchbar/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Q
from django.template.loader import render_to_string
from vehicles.models import Aplication

def search(request):
    query = request.GET.get('q', '')
    words = query.split()
    q_objects = Q()
    for word in words:
        q_objects &= (Q(segment__icontains=word) | Q(make__icontains=word) | Q(year__icontains=word) | Q(model__icontains=word))

    aplications = Aplication.objects.filter(q_objects)
    context = {'aplication_list': aplications}
    html = render_to_string('vehicles/aplication_rows.html', context)
    return JsonResponse({'html': html})

mysite/vehicles/templates/vehicles/aplication_list.html
{% extends "vehicles/base_bootstrap.html" %}

{% block navbar %}
    {% include "vehicles/navbar.html" %}
    {% endblock %}
    
    {% block content %}
    {% include "vehicles/base_table.html" %}


    <p>

    <p>
      <a href="{% url 'vehicles:make_list' %}">View makes</a>  |
      <a href="{% url 'vehicles:make_create' %}">Add a make</a>
    </p>
    <p>
      <a href="{% url 'vehicles:year_list' %}">View years</a> |
      <a href="{% url 'vehicles:year_create' %}">Add a year</a>
    </p>
    <p>
      <a href="{% url 'vehicles:model_list' %}">View models</a> |
      <a href="{% url 'vehicles:model_create' %}">Add a model</a>
    </p>
    <p>
      <a href="{% url 'vehicles:segment_list' %}">View Segments</a> |
      <a href="{% url 'vehicles:segment_create' %}">Add a segment</a>
    </p>
{% endblock %}

mysite/vehicles/templates/vehicles/base_table.html
{% load static %}
{% load crispy_forms_tags %}
{% load vehicles_extras %}

{% block content %}
<style>
    .centered-form {
        max-width: 600px;
        margin: 0 auto;
    }
    .table-responsive {
        max-height: 600px;
        overflow: auto;
        display: block;
        width: 100%;
    }
    .application-list-container {
        max-height: 100px;
        max-width: 400px;
        overflow-y: auto;
    }
    .application-list {
        list-style-type: none;
        padding: 0;
    }
    .btn-update {
        background-color: #7da0aa;
        color: white;
        width: 60px;
        text-align: center;
    }
    .btn-delete {
        background-color: #b4424e;
        color: white;
        width: 60px;
        text-align: center;
    }
    .table-responsive {
    max-height: 600px;
    overflow: auto;
    display: block;
    width: 100%;
    border: 1px solid #ddd;
}

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td{
        padding: 8px;
        text-align: left;
        vertical-align: middle;
        border: 1px solid #ddd;
        white-space: nowrap; /* Evita que el texto se divida en varias líneas */
        
    }

    th {
        background-color: #f2f2f2;
        font-weight: bold;
    }

    .application-list-container {
        max-height: 100px;
        max-width: 400px;
        overflow-y: auto;
        overflow-x: hidden; /* Para evitar desplazamiento horizontal */
    }
    .application-list {
        list-style-type: none;
        padding: 0;
    }
    .application-list li:hover {
        border-bottom: 1px solid #ccc;
        padding: 5px 0;
        background-color: #f3f8f8;
    }
    .clickable-row:hover {
        cursor: pointer;
        background-color: #f3f8f8; /* Cambia el color según tu preferencia */
    }

</style>

<div class="row">
    <div class="col-md-12">
        <h1>{{ title }} List</h1>

        {% if show_search_bar %}
            {% include "vehicles/search_bar.html" %}
        {% endif %}

        <div id="results">
            {% if object_list %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            {% for header in headers %}
                            <th>{{ header }}</th>
                            {% endfor %}
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="table-body">
                        {% for obj in object_list %}
                        <tr {% if has_detail_page %} class="clickable-row" data-href="{% url 'vehicles:aplication_detail' obj.id %}" {% endif %}>
                            {% for field in fields %}
                                <td>
                                    {% if title == "Aplication" %}
                                        {% if field == "segment_name" %}
                                            {{ obj.segment.segment }}
                                        {% elif field == "make_name" %}
                                            {{ obj.make.make }}
                                        {% elif field == "model_name" %}
                                            {{ obj.model.model }}
                                        {% elif field == "year_name" %}
                                            {{ obj.year.year }}
                                        {% elif field == "market_name" %}
                                            {{ obj.get_market_display }}
                                        {% endif %}
                                    {% elif title == "Part" %}
                                        {% if field == "sku" %}
                                            {{ obj.sku }}
                                        {% elif field == "name" %}
                                            {{ obj.name }}
                                        {% elif field == "categories" %}
                                            {% for category in obj.categories.all %}
                                                {{ category.category }}{% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                        {% elif field == "applications" %}
                                            <div class="application-list-container">
                                                <ul class="application-list">
                                                    {% for application in obj.applications.all|dictsort:"make.make" %}
                                                        <li>
                                                            {{ application.make.make }} > {{ application.model.model }} > {{ application.year.year }} > {{ application.segment.segment }}
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        {% elif field == "properties" %}
                                            {% for property in obj.properties.all %}
                                                {{ property.property }}: <b>{{ property.value }}<br></b>
                                            {% endfor %}
                                        {% elif field == "notes" %}
                                            <i>{{ obj.notes }}</i>
                                        {% elif field == "description" %}
                                            {{ obj.description }}
                                        {% endif %}
                                    {% endif %}
                                </td>
                            {% endfor %}
                            <td class="action-buttons">
                                <button type="button" class="btn btn-update btn-sm" data-bs-toggle="modal" data-bs-target="#updateModalTemplate" data-url="{% url update_url obj.id %}">Update</button>
                                <button type="button" class="btn btn-delete btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModalTemplate" data-url="{% url delete_url obj.id %}">Delete</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
                <p>There are no {{ title }}s in the list.</p>
            {% endif %}

            <!-- Pagination -->
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1">First</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if num == page_obj.number %}
                            <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                        {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

<!-- Modals for Update and Delete -->
<div class="modal fade" id="updateModalTemplate" tabindex="-1" aria-labelledby="updateModalLabelTemplate" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabelTemplate">Update {{ title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="updateFormTemplate" method="post">
                    {% csrf_token %}
                    <div id="updateFormContent"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" form="updateFormTemplate">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModalTemplate" tabindex="-1" aria-labelledby="deleteModalLabelTemplate" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabelTemplate">Delete {{ title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="deleteFormTemplate" method="post">
                    {% csrf_token %}
                    <p>Are you sure you want to delete this {{ title }}?</p>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script src="{% static 'vehicles/js/search_table.js' %}"></script>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const rows = document.querySelectorAll(".clickable-row");
        rows.forEach(row => {
            row.addEventListener("click", (event) => {
                if (!event.target.closest('.action-buttons')) {
                const href = row.dataset.href;
                if (href) {
                    window.location.href = href;
                }
            }
            });
        });
    });
</script>
{% endblock scripts %}

mysite/vehicles/templates/vehicles/category_form.html
{% extends "base_bootstrap.html" %}

{% block content %}

{% load crispy_forms_tags %}

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'vehicles:category_list' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/vehicles/templates/vehicles/navbar.html
{% load app_tags %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="width: 100%;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'vehicles:all' %}">Catalogo de partes</a>
    <ul class="navbar-nav">
      {% url 'ads:all' as x %}
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'vehicles:part_list' %}" role="button">Parts</a></li>
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'vehicles:all' %}" role="button">Vehicles</a></li>
      <li {% if request.get_full_path == x %}class="active"{% endif %}>
          <a class="nav-link" href="{% url 'vehicles:category_list' %}" role="button">Categories</a></li>
    
        
    </ul>
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        {% if user.is_staff %}
        <li>
           <a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a>
        </li>
        {% endif %}
      
      <li class="nav-item dropdown">
         <a class="nav-link dropdown-toggle" href="#" id="rightnavDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
            <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a></li>
        </ul>
       </li>
       {% else %}
       <li class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}